config/routes.rb
# routes.rbはURLを作るところ

require 'sidekiq/web'
# sidekiqをweb上で読み込むためのもの

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  # sidekiqでqueuesがどれくらい溜まっているのかweb上で確認するためのもの

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # development環境であれば/letter_openerのURLでLetterOpenerWebの内容が見れるようになるというもの。(送信したメールの確認のためのもの)

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'articles#index'
  # root toで/を意味する。何もなけれはarticleのindexを表示すると言う意味

  

  # resourcesとは色々なURLを作成する際に使う
  resources :articles 
    # resources :articles doでarticleのIDの下にURLを作る際に使う。例:id1の人の記事に何かコメントなどする場合id1のなかにURLを入れるというようなイメージ


  resources :accounts, only: [:show] do
  # 他のアカウントのプロフィールを見るためのもの
    resources :follows, only: [:create]
    # アカウントの中のフォローのURLの作成
    resources :unfollows, only: [:create]
    # アカウントの中のアカウントを消すためのURL
  end

  scope module: :apps do
    # scope moduleでコントローラーのみ変更。appsフォルダーについて

    resources :favorites, only: [:index]
    # resource :favoritesでプロフィールのURLを作成。favorites（いいねだけを表示する画面）は複数表示するためsをつける。

    resource :timeline, only: [:show]
    # タイムライン機能のURLの作成
    
    resource :profile, only: [:show, :edit, :update]
    # resource :profileでプロフィールのURLを作成。プロフィールはユーザーと紐付けられるのは一つなので単数。
  end

  namespace :api, defaults: {format: :json} do
    # namespaceURLもコントローラーも作成する。apiフォルダーについて変更。defaults{format: :json}でformat(htmlかjsonで表示するか)の指定できる

    scope '/articles/:article_id' do
      # scopeでURLのみ変更する。で先頭に/articles/:article_idを入れる

      resources :comments, only: [:index, :create]
      # resources :commentsでarticleIDのなかにcommentsのURLを作成している。
  
      resource :like, only: [:show, :create, :destroy]
      # resource :likeでarticleIDのなかにlikeのURLを作っている。
      # createの理由はlikesテーブルにレコードを作りいいねをしているためcreateになる
    end
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#

# Articleファイルのデータを保存するためにあるファイル
# article.rbはarticleファイルのルールを決めるファイル
# validatesでルールを決めている。validationで色々なルールを調べると良い
# validateで独自のルールを決めている。validatesとvalidateは違うので注意

class Article < ApplicationRecord
  has_one_attached :eyecatch
  # 画像のアップロードのためのもの

  has_rich_text :content
  # contentに対して強化したエディターを渡すという意味

  validates :title, presence: true
  # titleがないと保存しない

  validates :title, length: { minimum: 2, maximum: 100 }
  validates :title, format: { with: /\A(?!\@)/ }
  
  # validateで独自のルールの内容についてprivateで書いている。この場合titleとcontentの内容が100文字以上ではなければいけないという意味。

  validates :content, presence: true
  # contentがないと保存しない

  has_many :comments, dependent: :destroy
  # has_many commentsでArticleがたくさんのコメントを持っているという意味。記事から見てコメントは複数あるため複数形にする。
  # dependent: :destroyでこの記事が削除されたらコメントも削除するという意味。

  has_many :likes, dependent: :destroy
  # has_many :likes でいいねはたくさんの記事に行なっているという意味。複数形なのでlikesのsが大事
  # dependent: :destroyでユーザーが消されたら投稿の記事なども消すという意味。

  belongs_to :user
  # belongs_to :userで記事はユーザーと紐づいているという意味。


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # ArticlesControllerがApplicationControllerを継承していると言う意味(ApplicationControllerで書いてある内容を使える)

  before_action :set_article, only: [:show]
    # before_actionでarticles_controller.rb内で同じようなコードがある場合に使う。:set_articleの中に同じようなコードを入れてインスタンス変数で表示できるようにしている。only:[:show]でshowだけという意味。

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    # before_actionでarticles_controller.rb内で同じようなコードがある場合に使う。authenticate_user!はrailsのルールで全てのアプリがログインしていなければ使えないという意味。

  def index
    # 全ての画面の表示する際はrailsのルールでindexとしてあげなければならない
    # viewsのindexの設定
    @articles = Article.all
      # Article.allはArticleの中のデータを全て表うじするを言う意味
  end

  def show
  end

  def new
    @article = current_user.articles.build
      # @articleは空の箱、current_userでログインしているユーザーの値の取得、articles.buildでarticlesのユーザーとの関連性がある場合buildを使う。
  end

  def create
    @article = current_user.articles.build(article_params)
      # 上の文の@articleは空のインスタンスにデータを入れているだけ、current_userでログインしているユーザーと紐づける、articles.buildでarticlesのユーザーとの関連性がある場合buildを使う。

    if @article.save
      # @articleの情報を.saveで保存をしている
      redirect_to article_path(@article), notice: '保存できました。'
        # redirect_toで指定したリンクに飛ばすと言う意味でartidle_pathに飛ばすと言う意味。notice: 内容 で保存されたら内容を表示すると言う意味
    else
      flash.now[:error] = '保存に失敗しました。'
      render :new
        # render :newはnewの画面を表示すると言う意味。上の文では保存されなかったらnewの画面を表示という意味
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
      # @articleに空のデータを入れて、current_userでログインしているユーザーの取得、article.find(params[:id])でarticleのどのidのデータを編集するかという意味。
  end

  def update
    @article = current_user.articles.find(params[:id])
      # current_userでログインしているユーザーの取得、articles.find(params[:id])でidの指定という意味。

    if @article.update(article_params)
      # if @article.update(article_params)は保存できた場合という意味。

      redirect_to article_path(@article), notice: '更新できました'
        # redirect_toで指定したリンクに飛ばす。article_path(@article)でリンクの指定。noticeで更新できたら文字の表示という意味。
    else
      # flash.now[:error]でelseだったら更新できませんでしたと表示という意味。
      flash.now[:error] = '更新できませんでした'
      render :edit
        # render :editでeditファイルの表示(上の文更新できなかったらという意味)
    end
  end

    def destroy
      article = current_user.articles.find(params[:id])
        # current_userでログインしているユーザーの値の取得、articleに削除のデータを入れる。articles.find(params[:id])でidの取得。

      article.destroy!
        # article.destroy!でarticleのデータを削除するという意味。※destroyの最後に!をつけることで削除できなかった場合に例外を出すことができる。

      redirect_to root_path, notice: '削除しました'
        # redirect_toでリンクに飛ばす。root_pathがリンク。noticeで削除できた際に文字を表示する。
    end

  # privateはデータを保存する際に使う
  private
  def article_params
    # データ更新のためのもの
    params.require(:article).permit(:title, :content, :eyecatch)
  end
      # requireでarticleのキーを選択し、permitでarticleの中のこれだけは保存をすると言うのを選んでいる
      # ホームから投稿した際,:title, :content, :eyecatchの情報を抜き出してくると言う意味

  def set_article
    @article = Article.find(params[:id])
  end
    # articles_controller.rbの４行目で同じようなコードがある場合一つにまとめるように設定したがその内容が書いてある。

end

app/views/articles/_form.html.haml
-# 部分テンプレートノフォルダーは名前の最初に _ をつける

.container
  %ul
    - article.errors.full_messages.each do |message|
      %li= message
      -# 上の３文はarticle.rbのvalidatesなどで指定したルールとは違うことが起きた際にエラーのメッセージを表示してくれる。railsのルール。
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :eyecatch, 'アイキャッチ'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title
    %div
      = f.label :content, '内容'
    %div
      = f.rich_text_area :content
    = f.submit '保存', class: 'btn-primary'


-# form_withはフォームを作成する際に使う(投稿画面の作成などに使う)
-# form_withを使う際はmodel,url,methodを()の中で指定してあげる。
-# modelはどのformを更新しようとしていますか？と言う意味のため更新したいformをmodelに入れる
-# urlは送りたいurlを入れる
-# metodはpostなのかgetなのか入れる

    %div
      = f.label :eyecatch, 'アイキャッチ'
      上の二文はrailsのルールでラベルを作成する際に使う

    %div
      = f.text_field :title
      上の２文はhtmlで言うとinput typeのタグをrailsのルールで作成できる

    %div
      = f.text_area :content
      上の２文はhtmlで言うとinput typeのタグをrailsのルールで作成できる

     = f.submit '保存', class: 'btn-primary'
     上の２文はhtmlで言うボタンの作成をrailsのルールで作っている

app/views/articles/edit.html.haml
= render 'form', article: @article
-# render 'form'で_formの部分テンプレートを表示する

app/views/articles/index.html.haml
.container
  = render 'tabs'
  -# renderでtabsの表示をしている。※部分テンプレートを使う場合はフォルダーの前に_を入れる。
  - @articles.each do |article|
    = render 'commons/article', article: article
    -# renderでcommons/articleのフォルダーを表示している。article: articleはcommons/articleの中のarticleを表示していますよという意味。※４行目のarticleに情報がないためarticle: articleで情報を入れている。
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus
  -# link_toでhtmlで言うaタグのようなもの(この場合new_article_pathへリンクを飛ばすと言う意味)

  -# link_to のあとの new_aritcle_pathでどこのリンクに飛ばすか指定している(どのリンクに飛ばせばいいかわからない場合は rails/info でリンク先を確認する)
  
  -# - @articles.each do |article| は articleのデータを繰り返し表示すると言う意味

  -# .float_btn
  -#     %i.fa.fa-plus 
      上の２文を使うとfont-awesomeと言うツールを使っていてこの場合はプラスボタンの作成と言う意味になっている(アイコン作成に使う)。他のアイコンを使いたい場合は font-awesome調べたいアイコン名 で調べられる
      

app/views/articles/new.html.haml
= render 'form', article: @article
-# render 'form'で_formの部分テンプレートを表示する

app/views/articles/show.html.haml
.article#article-show{data: {article_id: @article.id}}
  - if @article.eyecatch.attached?
    -# articleの記事にアイキャッチ画像が設定されていたら
    .article_image
      = image_tag @article.eyecatch
      -# アイキャッチ画像を表示
  %h1.article_title= @article.title
  .article_detail
    = link_to account_path(@article.user) do
      -# 他のアカウントのプロフィールにリンクを飛ばしている
      = image_tag @article.user.avatar_image
      -# imgの画像のアカウントの選択
    %div
      %p= @article.author_name
      -# article.rbでauthor_nameの内容を書いている
      %p= @article.display_created_at
      -# 上のdisplay_created_atと入力すると日付の表示ができるようにarticle.rbで設定した。@articleでarticle.rbの設定が適用されている
      - if user_signed_in? && current_user.has_written?(@article)
        -# if user_signed_in?でログインしていたら、かつ、current_userで登録したユーザーの取得、has_written?(@article)でuser.rbで作成した情報を持ってきている。has_written?はコードがわかりやすくなるためにこのようにしている
        .article_detail_actions
          .dropdown
            = image_tag 'actions.svg', class: 'dropbtb'
            .dropdown-content.mini
              = link_to '編集する', edit_article_path(@article)
              -# 上の文の@articleはidを指定しないといけないため人ようとなる
              = link_to '削除する', article_path(@article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？'}
              -# link_toでは基本的にgetメソッドになってしまうためmethod: 'delete'でメソッドを指定してあげなければならない
              -# 上の文の@articleはidを指定しないといけないため必要となる

  .article_content
    = @article.content
  - if user_signed_in?
    -# もしサインインしていたら
    .article_heart.hidden.active-heart
      -# クラスのhiddenをscssで表示を消す用事してクリックされたら表示するようにする
      = image_tag 'heart-active.svg'
      -# heart-active.svgの表示
    .article_heart.hidden.inactive-heart
      = image_tag 'heart.svg'
      -# heart.svgの表示

.article
  %h2= I18n.t('articles.comment_list')
  -# localesのarticlesの中のcomment_listを表示する
  .comments-container

.container
  .btn-secondary.show-comment-form
    コメントを追加
  .comment-text-area.hidden
    = text_area_tag :comment_content, '', class: 'sm'
    -# railsルールでtext_area_tegはテキストエリアのタグを作成するためもの。comment_contentは名前。''の中は初期値。class: 'sm'で短めのテキストエリア。
    .btn-secondary.add-comment-button
      コメントを追加

= javascript_pack_tag 'article'
-# javascriptのpackの中のarticleを読み込める