config/routes.rb
# routes.rbはURLを作るところ

require 'sidekiq/web'
# sidekiqをweb上で読み込むためのもの

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  # sidekiqでqueuesがどれくらい溜まっているのかweb上で確認するためのもの

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # development環境であれば/letter_openerのURLでLetterOpenerWebの内容が見れるようになるというもの。(送信したメールの確認のためのもの)

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'articles#index'
  # root toで/を意味する。何もなけれはarticleのindexを表示すると言う意味

  

  # resourcesとは色々なURLを作成する際に使う
  resources :articles 
    # resources :articles doでarticleのIDの下にURLを作る際に使う。例:id1の人の記事に何かコメントなどする場合id1のなかにURLを入れるというようなイメージ


  resources :accounts, only: [:show] do
  # 他のアカウントのプロフィールを見るためのもの
    resources :follows, only: [:create]
    # アカウントの中のフォローのURLの作成
    resources :unfollows, only: [:create]
    # アカウントの中のアカウントを消すためのURL
  end

  scope module: :apps do
    # scope moduleでコントローラーのみ変更。appsフォルダーについて

    resources :favorites, only: [:index]
    # resource :favoritesでプロフィールのURLを作成。favorites（いいねだけを表示する画面）は複数表示するためsをつける。

    resource :timeline, only: [:show]
    # タイムライン機能のURLの作成
    
    resource :profile, only: [:show, :edit, :update]
    # resource :profileでプロフィールのURLを作成。プロフィールはユーザーと紐付けられるのは一つなので単数。
  end

  namespace :api, defaults: {format: :json} do
    # namespaceURLもコントローラーも作成する。apiフォルダーについて変更。defaults{format: :json}でformat(htmlかjsonで表示するか)の指定できる

    scope '/articles/:article_id' do
      # scopeでURLのみ変更する。で先頭に/articles/:article_idを入れる

      resources :comments, only: [:index, :create]
      # resources :commentsでarticleIDのなかにcommentsのURLを作成している。
  
      resource :like, only: [:show, :create, :destroy]
      # resource :likeでarticleIDのなかにlikeのURLを作っている。
      # createの理由はlikesテーブルにレコードを作りいいねをしているためcreateになる
    end
  end
end

app/views/commons/_article.html.haml
= link_to article_path(id: article.id) do
  .card
    - if article.eyecatch.attached?
      -# もしarticleの記事のアイキャッチ画像が設定されていたら
      .card_image
        = image_tag article.eyecatch
        -# アイキャッチ画像の表示
    .card_content
      .card_title
        = article.title
      .card_heart
        = image_tag 'heart.svg'
        %span= article.like_count
        -# いいねの数のカウント
      .card_detail
        = image_tag article.user.avatar_image
        %div
          %p= article.author_name
          -# article.rbでauthor_nameの内容を書いている
          %p= article.display_created_at

app/views/commons/_articles.html.haml
.container
  = render 'commons/tabs'
  -# renderでcommons/tabsの表示をしている。※部分テンプレートを使う場合はフォルダーの前に_を入れる。
  - articles.each do |article|
    = render 'commons/article', article: article
    -# renderでcommons/articleのフォルダーを表示している。article: articleはcommons/articleの中のarticleを表示していますよという意味。※４行目のarticleに情報がないためarticle: articleで情報を入れている。
  = link_to new_article_path do
    .float_btn
      %i.fa.fa-plus
  -# link_toでhtmlで言うaタグのようなもの(この場合new_article_pathへリンクを飛ばすと言う意味)

  -# link_to のあとの new_aritcle_pathでどこのリンクに飛ばすか指定している(どのリンクに飛ばせばいいかわからない場合は rails/info でリンク先を確認する)
  
  -# - @articles.each do |article| は articleのデータを繰り返し表示すると言う意味

  -# .float_btn
  -#     %i.fa.fa-plus 
      上の２文を使うとfont-awesomeと言うツールを使っていてこの場合はプラスボタンの作成と言う意味になっている(アイコン作成に使う)。他のアイコンを使いたい場合は font-awesome調べたいアイコン名 で調べられる

app/views/commons/_profile.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag user.avatar_image
      -# image_tagでアイコンの表示、current_userでログインされていれば、avater_imageの表示

    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{user.display_name}（#{user.age || '？歳'}・#{I18n.t("enum.genders.#{user.gender || 'unknown'}")}）
          -# @userで選択しているユーザーの、display_nameやageなどは他のフォルダーから持ってきている。
          -# １行に対して色々な文字を入れたい場合は#{}を使う
          -# I18n.tでymlフォルダーを表示という意味、enum.ja.ymlフォルダーのenumの中のgendersの中を表示、ログインされているプロフィールの性別。
        .profilePage_user_actionButton
          - if user == current_user
            -# もしユーザーが自分のログインしているユーザーだったら
            = link_to 'Edit', edit_profile_path
            -# Editで編集画面の表示
          - else
            - if current_user&.has_followed?(user)
              -# &でnillだったら実装しない
              -# ログインしているユーザーがuser.rbで指定した内容のhas_followed?(user)だったら
              = link_to 'Unfollow', account_unfollows_path(user), data: {method: 'post'}
            - else
              = link_to 'Follow', account_follows_path(user), data: {method: 'post'}
              -# Followを表示してフォローできるようにする。フォローしたらaccount_follows_path(user)で選択されているユーザーをフォロー。データーはpost。
      .profilePage_user_introduction
        = user.profile&.introduction

  - user.articles.each do |article|
    -# @userで選択しているユーザーの値を取得、articles.each doでarticleの記事情報を取得、|article|で値をaritcleで表示するという意味。
    = render 'commons/article', article: article
    -# renderで表示、'commons/article’を、articleの値はarticleを取得。

app/views/commons/_tabs.html.haml
-# 部分テンプレートノフォルダーは名前の最初に _ をつける
.tabs
  .tabs_item{class: "#{add_active_class(root_path)}"}
    -# add_active_classで指定したパスが今のページか調べる。もしこのページがroot_pathのページだったらクラス名をactiveとする。activeになった方がscssで指定した色になるためどちらの画面を開いているのかわかる。
    = link_to '新規記事一覧', root_path
    -# 新規記事一覧を押すとroot_pathを表示

  .tabs_item{class: "#{add_active_class(timeline_path)}"}
    -# add_active_classで指定したパスが今のページか調べる。もしこのページがtimeline_pathのページだったらクラス名をactiveとする。activeになった方がscssで指定した色になるためどちらの画面を開いているのかわかる。
    = link_to 'タイムライン', timeline_path 
    -# タイムラインを押すとtimeline_pathを表示

    -# add_active_classは appの中のhelpersの中のtabs_helper.rbで内容を指定している。