config/routes.rb
# routes.rbはURLを作るところ

require 'sidekiq/web'
# sidekiqをweb上で読み込むためのもの

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
  # sidekiqでqueuesがどれくらい溜まっているのかweb上で確認するためのもの

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # development環境であれば/letter_openerのURLでLetterOpenerWebの内容が見れるようになるというもの。(送信したメールの確認のためのもの)

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'articles#index'
  # root toで/を意味する。何もなけれはarticleのindexを表示すると言う意味

  

  # resourcesとは色々なURLを作成する際に使う
  resources :articles 
    # resources :articles doでarticleのIDの下にURLを作る際に使う。例:id1の人の記事に何かコメントなどする場合id1のなかにURLを入れるというようなイメージ


  resources :accounts, only: [:show] do
  # 他のアカウントのプロフィールを見るためのもの
    resources :follows, only: [:create]
    # アカウントの中のフォローのURLの作成
    resources :unfollows, only: [:create]
    # アカウントの中のアカウントを消すためのURL
  end

  scope module: :apps do
    # scope moduleでコントローラーのみ変更。appsフォルダーについて

    resources :favorites, only: [:index]
    # resource :favoritesでプロフィールのURLを作成。favorites（いいねだけを表示する画面）は複数表示するためsをつける。

    resource :timeline, only: [:show]
    # タイムライン機能のURLの作成
    
    resource :profile, only: [:show, :edit, :update]
    # resource :profileでプロフィールのURLを作成。プロフィールはユーザーと紐付けられるのは一つなので単数。
  end

  namespace :api, defaults: {format: :json} do
    # namespaceURLもコントローラーも作成する。apiフォルダーについて変更。defaults{format: :json}でformat(htmlかjsonで表示するか)の指定できる

    scope '/articles/:article_id' do
      # scopeでURLのみ変更する。で先頭に/articles/:article_idを入れる

      resources :comments, only: [:index, :create]
      # resources :commentsでarticleIDのなかにcommentsのURLを作成している。
  
      resource :like, only: [:show, :create, :destroy]
      # resource :likeでarticleIDのなかにlikeのURLを作っている。
      # createの理由はlikesテーブルにレコードを作りいいねをしているためcreateになる
    end
  end
end

app/views/layouts/_footer.html.haml
%footer.footer-container
  - if I18n.locale == :en
    -# I18n.localeが英語だったら
    = link_to '日本語', url_for(locale: :ja)
    -# url_forでパラメーターのみURLを変更できる。locale: :ja日本語に
  - else
    = link_to 'English', url_for(locale: :en)
    -# url_forでパラメーターのみURLを変更できる。locale: :en英語に

app/views/layouts/application.html.haml
-# layoutsは共通化されたテンプレート, 全ての画面に表示したいことを書く

!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlogApp
    = csrf_meta_tags
    -# csrf_meta_tagsでcsrfToken(鍵)を取得してそれと一緒ではないとToken設定されている箇所はTokenがないと操作できないようにしている
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    -# javascript_pack_tagはjavascriptのコードを読み込むためのもの

    %meta{:content => "width=device-width,initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    -# font-awesomeとはアイコンなどを表示するするためのツール

  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          -# !current_page?(root_path)でホームにいなかったら戻るボタンの表示。※!でホームにいなかったらとなっている
          = link_to :back do
            -# link_to :back doでホームに戻る。railsのルール
            = image_tag 'back.svg', class: 'header_back'
      %p.header_pageTitle 
        = link_to 'BlogApp', root_path
      - if user_signed_in?
        -# if user_signed_in?はログイン機能で使用される。もしログインしていればという意味。railsのルール。
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          -# アイコンの画像の設定
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'お気に入り', favorites_path
            = link_to 'ログアウト', destroy_user_session_path, date: { method: 'delete' }
      - else
        -# elseのためログインしていなければという意味
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'

    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => "key"}= value
          -# 上の４文はarticle_controllerで保存ができた、保存できなかった際notice、Flashで文字の表示をしようとしたがそれを表示するための文
    = yield

    = render 'layouts/footer'
    -# renderで呼び込む。layoutsのfooter部分テンプレートを